// <auto-generated />
using System;
using FootballAnalysis.Data.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballAnalysis.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionSeason", b =>
                {
                    b.Property<Guid>("CompetitionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeasonsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionsId", "SeasonsId");

                    b.HasIndex("SeasonsId");

                    b.ToTable("CompetitionSeason");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Attendance")
                        .HasColumnType("int");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("KickOff")
                        .HasColumnType("datetime2");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AlternativePositions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.PlayerMatchStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManOfTheMatch")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Started")
                        .HasColumnType("bit");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasSubstitutedOff")
                        .HasColumnType("bit");

                    b.Property<bool>("WasSubstitutedOn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerMatchStats");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaptainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFormation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.TeamMatchStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMatchStats");
                });

            modelBuilder.Entity("CompetitionSeason", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Match", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Player", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.PlayerMatchStats", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Match", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Player", "Player")
                        .WithMany("MatchStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.Goalkeepering", "Goalkeepering", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AccurateLongBalls")
                                .HasColumnType("int");

                            b1.Property<int>("AccuratePasses")
                                .HasColumnType("int");

                            b1.Property<int>("ActedAsSweeper")
                                .HasColumnType("int");

                            b1.Property<double>("FacedxGOT")
                                .HasColumnType("float");

                            b1.Property<int>("GoalsConceded")
                                .HasColumnType("int");

                            b1.Property<double>("GoalsPrevented")
                                .HasColumnType("float");

                            b1.Property<int>("HighClaim")
                                .HasColumnType("int");

                            b1.Property<int>("LongBalls")
                                .HasColumnType("int");

                            b1.Property<int>("Passes")
                                .HasColumnType("int");

                            b1.Property<int>("Saves")
                                .HasColumnType("int");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerAnalysis", "Analysis", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AnalystNotes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PerformanceSummary")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerAttack", "PlayerAttack", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BigChancesMissed")
                                .HasColumnType("int");

                            b1.Property<int>("DribblesAttempted")
                                .HasColumnType("int");

                            b1.Property<int>("Goals")
                                .HasColumnType("int");

                            b1.Property<int>("ShotsOnTarget")
                                .HasColumnType("int");

                            b1.Property<int>("SuccessfulDribbles")
                                .HasColumnType("int");

                            b1.Property<int>("TotalShots")
                                .HasColumnType("int");

                            b1.Property<int>("TouchesInOppositionBox")
                                .HasColumnType("int");

                            b1.Property<double>("XG")
                                .HasColumnType("float");

                            b1.Property<double>("XGOT")
                                .HasColumnType("float");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerDefence", "PlayerDefence", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Blocks")
                                .HasColumnType("int");

                            b1.Property<int>("Clearance")
                                .HasColumnType("int");

                            b1.Property<int>("DefensiveContributions")
                                .HasColumnType("int");

                            b1.Property<int>("DribbledPast")
                                .HasColumnType("int");

                            b1.Property<int>("HeadedClearances")
                                .HasColumnType("int");

                            b1.Property<int>("Interceptions")
                                .HasColumnType("int");

                            b1.Property<int>("Recoveries")
                                .HasColumnType("int");

                            b1.Property<int>("Tackles")
                                .HasColumnType("int");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerDiscipline", "PlayerDiscipline", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FoulsCommitted")
                                .HasColumnType("int");

                            b1.Property<int>("RedCards")
                                .HasColumnType("int");

                            b1.Property<int>("WasFouled")
                                .HasColumnType("int");

                            b1.Property<int>("YellowCards")
                                .HasColumnType("int");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerDuels", "PlayerDuels", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AerialDuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("DuelsLost")
                                .HasColumnType("int");

                            b1.Property<int>("DuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("GroundDuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("TotalAerialDuels")
                                .HasColumnType("int");

                            b1.Property<int>("TotalGroundDuels")
                                .HasColumnType("int");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerPasses", "PlayerPasses", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AccurateCrosses")
                                .HasColumnType("int");

                            b1.Property<int>("AccurateLongBalls")
                                .HasColumnType("int");

                            b1.Property<int>("AccuratePasses")
                                .HasColumnType("int");

                            b1.Property<int>("Assists")
                                .HasColumnType("int");

                            b1.Property<int>("ChancesCreated")
                                .HasColumnType("int");

                            b1.Property<int>("CrossesAttempted")
                                .HasColumnType("int");

                            b1.Property<int>("LongBallsAttempted")
                                .HasColumnType("int");

                            b1.Property<int>("PassesAttempted")
                                .HasColumnType("int");

                            b1.Property<int>("PassesIntoFinalThird")
                                .HasColumnType("int");

                            b1.Property<int>("Touches")
                                .HasColumnType("int");

                            b1.Property<double>("XA")
                                .HasColumnType("float");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.PlayerStats", "PlayerStats", b1 =>
                        {
                            b1.Property<Guid>("PlayerMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("FotmobRating")
                                .HasColumnType("float");

                            b1.Property<int>("MinutesPlayed")
                                .HasColumnType("int");

                            b1.Property<double>("SofascoreRating")
                                .HasColumnType("float");

                            b1.HasKey("PlayerMatchStatsId");

                            b1.ToTable("PlayerMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMatchStatsId");
                        });

                    b.Navigation("Analysis")
                        .IsRequired();

                    b.Navigation("Goalkeepering")
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("PlayerAttack")
                        .IsRequired();

                    b.Navigation("PlayerDefence")
                        .IsRequired();

                    b.Navigation("PlayerDiscipline")
                        .IsRequired();

                    b.Navigation("PlayerDuels")
                        .IsRequired();

                    b.Navigation("PlayerPasses")
                        .IsRequired();

                    b.Navigation("PlayerStats")
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Team", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Player", "Captain")
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.TeamMatchStats", b =>
                {
                    b.HasOne("FootballAnalysis.Data.Domain.Models.Match", "Match")
                        .WithMany("TeamStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballAnalysis.Data.Domain.Models.Team", "Team")
                        .WithMany("MatchStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchAnalysis", "MatchAnalysis", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AnalystNotes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TacticalNotes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchAttackingZones", "MatchAttackingZones", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CenterAttack")
                                .HasColumnType("int");

                            b1.Property<int>("LeftAttack")
                                .HasColumnType("int");

                            b1.Property<int>("RightAttack")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchDefence", "MatchDefence", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Blocks")
                                .HasColumnType("int");

                            b1.Property<int>("Clearances")
                                .HasColumnType("int");

                            b1.Property<int>("Interceptions")
                                .HasColumnType("int");

                            b1.Property<int>("KeeperSaves")
                                .HasColumnType("int");

                            b1.Property<int>("Tackles")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchDiscipline", "MatchDiscipline", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FoulsCommitted")
                                .HasColumnType("int");

                            b1.Property<int>("RedCards")
                                .HasColumnType("int");

                            b1.Property<int>("YellowCards")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchDuels", "MatchDuels", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AerialDuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("AerialDuelsWonPercentage")
                                .HasColumnType("int");

                            b1.Property<int>("DuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("GroundDuelsWon")
                                .HasColumnType("int");

                            b1.Property<int>("GroundDuelsWonPercentage")
                                .HasColumnType("int");

                            b1.Property<int>("SuccessfulDribbles")
                                .HasColumnType("int");

                            b1.Property<int>("SuccessfulDribblesPercentage")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchExpectedGoals", "MatchExpectedGoals", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("NonPenaltyXG")
                                .HasColumnType("float");

                            b1.Property<double>("OpenPlayXG")
                                .HasColumnType("float");

                            b1.Property<double>("SetPlayXG")
                                .HasColumnType("float");

                            b1.Property<double>("XG")
                                .HasColumnType("float");

                            b1.Property<double>("XGOT")
                                .HasColumnType("float");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchPasses", "MatchPasses", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AccurateCrosses")
                                .HasColumnType("int");

                            b1.Property<int>("AccurateCrossesPercentage")
                                .HasColumnType("int");

                            b1.Property<int>("AccurateLongBalls")
                                .HasColumnType("int");

                            b1.Property<int>("AccurateLongBallsPercentage")
                                .HasColumnType("int");

                            b1.Property<int>("AccuratePasses")
                                .HasColumnType("int");

                            b1.Property<int>("Offsides")
                                .HasColumnType("int");

                            b1.Property<int>("OppositionHalf")
                                .HasColumnType("int");

                            b1.Property<int>("OwnHalf")
                                .HasColumnType("int");

                            b1.Property<int>("Passes")
                                .HasColumnType("int");

                            b1.Property<int>("Throws")
                                .HasColumnType("int");

                            b1.Property<int>("TouchesInOppositionBox")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchShots", "MatchShots", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BlockedShots")
                                .HasColumnType("int");

                            b1.Property<int>("HitWoodwork")
                                .HasColumnType("int");

                            b1.Property<int>("ShotsInsideBox")
                                .HasColumnType("int");

                            b1.Property<int>("ShotsOffTarget")
                                .HasColumnType("int");

                            b1.Property<int>("ShotsOnTarget")
                                .HasColumnType("int");

                            b1.Property<int>("ShotsOutsideBox")
                                .HasColumnType("int");

                            b1.Property<int>("TotalShots")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.OwnsOne("FootballAnalysis.Data.Domain.ValueObjects.MatchStats", "MatchStats", b1 =>
                        {
                            b1.Property<Guid>("TeamMatchStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BigChances")
                                .HasColumnType("int");

                            b1.Property<int>("BigChancesMissed")
                                .HasColumnType("int");

                            b1.Property<int>("Corners")
                                .HasColumnType("int");

                            b1.Property<int>("OppositionGoals")
                                .HasColumnType("int");

                            b1.Property<int>("Possession")
                                .HasColumnType("int");

                            b1.Property<int>("TeamGoals")
                                .HasColumnType("int");

                            b1.HasKey("TeamMatchStatsId");

                            b1.ToTable("TeamMatchStats");

                            b1.WithOwner()
                                .HasForeignKey("TeamMatchStatsId");
                        });

                    b.Navigation("Match");

                    b.Navigation("MatchAnalysis")
                        .IsRequired();

                    b.Navigation("MatchAttackingZones")
                        .IsRequired();

                    b.Navigation("MatchDefence")
                        .IsRequired();

                    b.Navigation("MatchDiscipline")
                        .IsRequired();

                    b.Navigation("MatchDuels")
                        .IsRequired();

                    b.Navigation("MatchExpectedGoals")
                        .IsRequired();

                    b.Navigation("MatchPasses")
                        .IsRequired();

                    b.Navigation("MatchShots")
                        .IsRequired();

                    b.Navigation("MatchStats")
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Competition", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Match", b =>
                {
                    b.Navigation("PlayerStats");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Player", b =>
                {
                    b.Navigation("MatchStats");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Season", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("FootballAnalysis.Data.Domain.Models.Team", b =>
                {
                    b.Navigation("MatchStats");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
